### PR TITLE
added accuracy

### PR DESCRIPTION
**Pull request by 0merjavaid**
This is a python file that helps a developer to check for accuracy of detection after training model.
you give path to annotations(test/validation set) and predicted JSON. then it will calculate accuracy using F1 measure.

### CODE REVIEW

**Comment by tankienleong** [comment]
Hi @0merjavaid , thanks for your great works! May I know where you get the equation to calculate the accuracy? If I not mistaken, the equation to calculate the F1 score should be 

`F1 = 2 * (precision * recall) / (precision + recall)`

but your code is different from my understandings.

**Comment by 0merjavaid** [comment]
https://chrisalbon.com/machine-learning/precision_recall_and_F1_scores.html
Check the formula for Accuracy. 
image


Or in simple words we have TN=TP => 2TP/(2TP+FP+FN)

**Comment by tankienleong** [comment]
I see. Thank you very much!

**Comment by 4F2E4A2E** [comment]
Could it be possible, that false positives and true positives [are switched in places](https://github.com/thtrieu/darkflow/pull/377/commits/04fb5657cd925585d79ca864427f358d647b6e52#diff-3f4bdae712082bf9572f83bcacddd5ecR155)?

This is the result from the accuracy.py:
`undetected: 6     True positives: 1    False positives: 3`

And this is the real marked in the boxes:
`undetected: 6     True positives: 3    False positives: 1`

**Comment by 0merjavaid** [comment]
Can you share the box for which its not performing correct.
bcz it worked correctly with my dataset.

**Comment by tankienleong** [comment]
The code also worked correctly with my dataset.

**Comment by merryHunter** [comment]
I also have doubts about correct version of the code. If you google for IOU, you'll find a link to a blog where this code was created, and there is yet a bug. Also, accuracy is not the best metric, much better metric is mean average precision.

**Comment by tankienleong** [comment]
Hi @merryHunter , can you please share us the link to the blog where this code was created. Thank you.

**Comment by merryHunter** [comment]
@tankienleong  [here](http://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/)

**Comment by QueenJuliaZxx** [comment]
hi,you,what kind of accuracy it caculated,does it mean I first trained on my dateset thenuse this model I trained to predect the image in my testImg ,and then run this .py,but could you tell me ,I just use 10 image to test  the model I trained ,and the accuracy of the ten image can show the accuracy of the model I trained.thank you very much,

**Comment by 0merjavaid** [comment]
@QueenJuliaZxx  it will simply check the predicted results against the actual annotations and will calculate mean Average precision, Like in your case it will calculate the mean average precision(mAP) of those 10 images being tested. according to formula described above.

**Comment by SiNcSaD** [comment]
Hi, @0merjavaid 
I want to plot Recall-Precision Curve. In your code, how to calculate recall and precision? Because I do not know how to get FN. Hope you can help me, thank you.

**Comment by onurbarut** [comment]
@SiNcSaD hey, 

have you found out how to plot recall-precision curve? I opened an issue about this here #532

**Comment by srhtyldz** [comment]
Can you please explain more spesificially  ? How can i implement this code ? how does it work ?

**Comment by jkstyle2** [comment]
Guys, how can I get the json files as the code requires?

**Comment by srhtyldz** [comment]
> Guys, how can I get the json files as the code requires?

This is your test result.

**Pull request closed without merging**
